services:
  agent-server:
    build:
      context: .
    container_name: ngs-agent-server
    command: >
      bash -c "
      echo 'Activating ngs_env and starting agent server...';
      source /opt/conda/bin/activate ngs_env;
      exec uvicorn agent.server:app --host 0.0.0.0 --port 8001 --reload
      "
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./config/.env:/app/config/.env
